[package]
name = "steamworks"
version = "0.0.14"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.0.1"
bitflags = "1.0.4"
chrono = "0.4.6"
crossbeam-channel = "0.4.0"
derive_more = "0.99.1"
enum-primitive-derive = "0.1.2"
genawaiter = { version = "0.2.2", features = ["futures03"] }
futures = "0.3.1"
num-traits = "0.2.6"
once_cell = "1.2.0"
parking_lot = "0.10.0"
slotmap = "0.4.0"
snafu = "0.6.0"
steamworks-sys = { path = "./steamworks-sys" }
